baseURL = 'https://3santree.netlify.app/'
languageCode = 'en-us'
title = 'Manchester'
description = 'Another corner in internet'
theme = 'diary'

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/about"
name = "About"
weight = 4